name: BuildTestDeploy
on:
  workflow_dispatch:
  push:
    tags:
      - "Abstraction-v[0-9]+.[0-9]+.[0-9]+"
      - "DI-v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.runsettings'
      - 'LICENSE.txt'
      - 'README.md'
  
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.runsettings'
      - 'LICENSE.txt'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-build-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    uses: Vectron/GithubWorkflows/.github/workflows/BuildAndTest.yml@main
    with:
      os: ${{ matrix.os }}
      dotnet_version: 8.0.x
      solution_file: Vectron.Extensions.DependencyInjection.sln

  call-deploy-preview:
    if: ${{!contains(github.ref, 'refs/tags/')}}
    needs: call-build-test
    permissions:
      packages: write
    uses: Vectron/GithubWorkflows/.github/workflows/DeployNugetGithub.yml@main
    with:
      os: ubuntu-latest
      dotnet_version: 8.0.x
      solution_file: Vectron.Extensions.DependencyInjection.sln
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}

  call-deploy-abstraction:
    if: contains(github.ref, 'refs/tags/Abstraction-v')
    needs: call-build-test
    permissions:
      packages: write
    uses: Vectron/GithubWorkflows/.github/workflows/DeployNugetGithub.yml@main
    with:
      os: ubuntu-latest
      dotnet_version: 8.0.x
      solution_file: src/Vectron.Extensions.DependencyInjection.Abstraction/Vectron.Extensions.DependencyInjection.Abstraction.csproj
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}

  call-deploy-di:
    if: contains(github.ref, 'refs/tags/DI-v')
    needs: call-build-test
    permissions:
      packages: write
    uses: Vectron/GithubWorkflows/.github/workflows/DeployNugetGithub.yml@main
    with:
      os: ubuntu-latest
      dotnet_version: 8.0.x
      solution_file: src/Vectron.Extensions.DependencyInjection/Vectron.Extensions.DependencyInjection.csproj
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
      

  call-release:
    needs: call-build-test
    permissions:
      deployments: write
      contents: write
    uses: Vectron/GithubWorkflows/.github/workflows/CreateRelease.yml@main
